version: '3.8'

services:
  pioneer3at:
    build: .
    image: pioneer3at_utalca:noetic
    container_name: pioneer3at_ros
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/root/catkin_ws/src:rw
    command: bash
